// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFbtEvdf_g8FPmzYL37gxyKajacfs8dCI',
    appId: '1:60943091730:web:88179e6d7e8d4177e330cb',
    messagingSenderId: '60943091730',
    projectId: 'roadrescue-f659b',
    authDomain: 'roadrescue-f659b.firebaseapp.com',
    storageBucket: 'roadrescue-f659b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFognjjNVW-hYQD-qyU-4UQkrJpnXSDGA',
    appId: '1:60943091730:android:a40a7401da2a7cf5e330cb',
    messagingSenderId: '60943091730',
    projectId: 'roadrescue-f659b',
    storageBucket: 'roadrescue-f659b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj7fgynvaghSOZiK_dc25lYmczLI31IrQ',
    appId: '1:60943091730:ios:aff51b8f07637338e330cb',
    messagingSenderId: '60943091730',
    projectId: 'roadrescue-f659b',
    storageBucket: 'roadrescue-f659b.firebasestorage.app',
    iosBundleId: 'com.example.roadRescue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj7fgynvaghSOZiK_dc25lYmczLI31IrQ',
    appId: '1:60943091730:ios:aff51b8f07637338e330cb',
    messagingSenderId: '60943091730',
    projectId: 'roadrescue-f659b',
    storageBucket: 'roadrescue-f659b.firebasestorage.app',
    iosBundleId: 'com.example.roadRescue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFbtEvdf_g8FPmzYL37gxyKajacfs8dCI',
    appId: '1:60943091730:web:0424d1b51ee8df31e330cb',
    messagingSenderId: '60943091730',
    projectId: 'roadrescue-f659b',
    authDomain: 'roadrescue-f659b.firebaseapp.com',
    storageBucket: 'roadrescue-f659b.firebasestorage.app',
  );
}
